### PR TITLE
include tidyr content; still need to add it into the table of content…

### PR DESCRIPTION
**Pull request by mikoontz**
…s file.

No modification from the R-DAVIS-week content. Just making sure I get the workflow right. I only committed the .Rmd document (i.e., not the generated .html or the lesson-tidyr_files directory, which should all be created upon site build)

I also didn't modify the site YAML yet.

### CODE REVIEW

**Comment by mikoontz** [comment]
Meant to say: This does build the site on my machine.

**Comment by ryanpeek** [comment]
Looks good!

**Comment by ryanpeek** [comment]
Also, should we have the process that whomever reviews and merges the pull should then delete the branch? Or the person who makes the pull request should delete the branch? It's not something that's necessary, but more a housecleaning/tidying sort of thing we may want to implement.

**Comment by ryanpeek** [comment]
@mikoontz, do you want to delete this branch, or would you like me too? It's merged and we should prune our repo down a bit after things get merged.

**Pull request merged**
